### Site Settings ###
title               : Oanh Le.
description         : >-
                      Hi, I'm Oanh 👋
                      Welcome to my home on the Internet

baseurl             : ""                                # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : oanhgle/oanhgle.github.io    
remote_theme        : oanhgle/oanhgle.github.io


### Plugins ###
# url: "https://oanhgle.github.io"                        # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  # - jemoji
  - jekyll-sitemap


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Oanh Le
  image             : https://i.imgur.com/12FowHM.png
  email             : oanhngle@gmail.com
  github            : oanhgle
  linkedin          : ohle



### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: Oanh 


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

github: [metadata]